name: Java CI with Gradle

on:
  push:
    branches: [ "develop_hj" ]
  pull_request:
    branches: [ "develop_hj" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/gasannes:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gasannes:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/gasannes:latest

            # Stop and remove existing container if it exists
            if [ "$(docker ps -q)" ]; then
              docker stop $(docker ps -q)
            fi

            if [ "$(docker ps -aq --filter 'status=exited')" ]; then
              docker rm $(docker ps -aq --filter 'status=exited')
            fi

            # Run the new container
            docker run -d --name gasannes_app --log-driver=syslog -p 8080:8080 -e SPRING_PROFILES_ACTIVE=dev ${{ secrets.DOCKER_USERNAME }}/gasannes:latest

            # Remove unused images to free 
            docker image prune -a -f
